version: "3.8"
services:
  localstack:
    container_name: "localstack_main"
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda,dynamodb
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "./localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
