quarkus:
  lambda:
    handler: create-order
  dynamodb:
    aws:
      region: sa-east-1
      credentials:
        type: static
        static-provider:
          access-key-id: test-key
          secret-access-key: test-secret
  log:
    level: DEBUG